import type { Plugin } from "@opencode-ai/plugin"

/**
 * Config File Protection Plugin
 * 
 * Blocks direct writes to configuration/package management files.
 * Forces agents to use proper CLI tools instead of hand-writing configs.
 * 
 * This prevents fake version numbers and non-existent packages.
 */

// Patterns for protected files
const PROTECTED_PATTERNS = [
  /package\.json$/,
  /package-lock\.json$/,
  /bun\.lockb$/,
  /yarn\.lock$/,
  /pnpm-lock\.yaml$/,
]

const getInstructions = (filePath: string): string => {
  const fileName = filePath.split("/").pop() || filePath
  
  if (fileName === "package.json") {
    return `
BLOCKED: Direct writes to package.json are not allowed.

Use CLI commands instead:
  - Initialize: bun init -y (or npm init -y)
  - Add deps: bun add <package> (or npm install <package>)
  - Add dev deps: bun add -d <package> (or npm install -D <package>)
  - Remove: bun remove <package> (or npm uninstall <package>)

To modify scripts or other fields, use:
  - bun pkg set scripts.build="next build"
  - npm pkg set scripts.build="next build"

NEVER hand-write package.json - package versions will be wrong!
`
  }
  
  if (fileName.includes("lock")) {
    return `
BLOCKED: Lock files should never be written directly.

Lock files are auto-generated by package managers:
  - bun.lockb is created by: bun install
  - package-lock.json is created by: npm install
  - yarn.lock is created by: yarn install
  - pnpm-lock.yaml is created by: pnpm install

Run the appropriate install command to generate/update lock files.
`
  }
  
  return `BLOCKED: ${fileName} should be managed by CLI tools, not written directly.`
}

export const ConfigFileProtection: Plugin = async ({ directory }) => {
  console.log(`[ConfigFileProtection] Loaded for directory: ${directory || "unknown"}`)
  
  return {
    "tool.execute.before": async (input, output) => {
      const toolName = (input?.tool ?? "").toLowerCase().trim()
      
      // Only intercept write and edit tools
      if (toolName !== "write" && toolName !== "edit") {
        return
      }
      
      // Get the file path from args
      const filePath: string = output?.args?.filePath || output?.args?.file || ""
      
      if (!filePath) {
        return
      }
      
      // Check if this file is protected
      const isProtected = PROTECTED_PATTERNS.some(pattern => pattern.test(filePath))
      
      if (isProtected) {
        const instructions = getInstructions(filePath)
        throw new Error(instructions)
      }
    },
  }
}

export default ConfigFileProtection
